# Generated by Django 3.1.6 on 2021-06-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='atd_percent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(null=True),
        ),
    ]
